#!/bin/sh

XRESOURCES="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"

# merge the xresources if there is one
[[ -f $XRESOURCES ]] && xrdb -merge $XRESOURCES

# this will swap caps lock and esc, and make the repeated keys speed faster
# see the script in ~/.local/scripts
remaps &

# start
case "$1" in
  i3) exec i3 ;;
  gnome) exec gnome-session ;;
  *) exit 1
esac
