#! /bin/sh

case "$1" in
  maria)
    systemctl status mariadb | grep -q "inactive"
    if [[ $? -eq 0 ]]; then
      sudo systemctl enable --now mariadb
      [[ $? -eq 0 ]] && echo "Restarting MariaDB service" || echo "Cannot
      restart MariaDB service"
    else
      sudo systemctl stop mariadb
      sudo systemctl disable mariadb
      [[ $? -eq 0 ]] && echo "Stopping MariaDB service" || echo "Cannot stop
      MariaDB service"
    fi
    ;;
  *)
    echo "I don't know what to do?"
    exit 1
    ;;
esac
