#! /bin/sh

CURRENT=$(asusctl profile -p | sed 's/Active profile is \(.*\)/\1/')

case $1 in
  status)
    echo "The current profile is $CURRENT"
    exit 0
    ;;
esac


# is the fan-curve of the current profile enabled?
# disable the output of grep with q
asusctl fan-curve --get-enabled | grep $CURRENT -q

if [[ $? -eq 0 ]]
then
  asusctl fan-curve -m $CURRENT -e false
  echo "The curve $CURRENT is disabled"
else
  asusctl fan-curve -m $CURRENT -e true
  echo "The curve $CURRENT is enabled."
fi
